INSERT INTO POST(VERSION, CREATE_TIME, UPDATE_TIME, TITLE, BODY) VALUES(0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'TITLE 1', 'BODY 1');
INSERT INTO POST(VERSION, CREATE_TIME, UPDATE_TIME, TITLE, BODY) VALUES(0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'TITLE 2', 'BODY 2');
INSERT INTO POST(VERSION, CREATE_TIME, UPDATE_TIME, TITLE, BODY) VALUES(0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'TITLE 3', 'BODY 3');
INSERT INTO POST(VERSION, CREATE_TIME, UPDATE_TIME, TITLE, BODY) VALUES(0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'TITLE 4', 'BODY 4');
